import Image from "next/image";
import Link from "next/link";
import { getCategories, getProductPage, getOutlets } from "@/lib/api";
import Icon, { IconName } from "@/components/Icon";
import ProductCard from "@/components/ProductCard";

const collections: { name: string; icon: IconName; search: string }[] = [
  { name: "Vegetables", icon: "leaf", search: "vegetable" }, { name: "Fruits", icon: "apple", search: "fruit" },
  { name: "Pantry staples", icon: "box", search: "rice" }, { name: "Dairy & eggs", icon: "cup", search: "egg" },
  { name: "Home essentials", icon: "home", search: "home" }, { name: "Explore everything", icon: "grid", search: "" },
];

export default async function HomePage() {
  const [categories, catalogue, featured, flagships, districts] = await Promise.all([getCategories(), getProductPage({ page_size: "8" }), getProductPage({ page_size: "8", is_featured: "true" }), getOutlets("", 1, "", "flagship"), getOutlets("", 1, "", "district")]);
  const products = featured?.results.length ? featured.results : catalogue?.results;
  return <>
    <section className="home-hero" aria-labelledby="hero-title"><div className="hero-copy"><span className="eyebrow">A fresh take on everyday</span><h1 id="hero-title">Good things.<br />Closer to <em>home.</em></h1><p>From fresh finds to everyday essentials. Discover your next favourite, all in one simple shop.</p><div className="hero-buttons"><Link href="/products" className="button-primary">Explore the marketplace <Icon name="arrow" width={16} height={16} /></Link><Link href="/outlets" className="button-secondary">Find an outlet</Link></div><span className="hero-footnote"><Icon name="bag" />Your picks. Your place. Pay on delivery.</span></div><div className="hero-art"><Image src="/images/market-basket.png" alt="A woven basket filled with leafy greens, tomatoes, lemons and bread" fill priority sizes="(max-width: 760px) 100vw, 650px" /><div className="hero-sticker"><Icon name="leaf" /><span><strong>A little goodness, every day.</strong><small>Make room for your everyday favourites</small></span></div></div></section>
    <div className="network-strip"><span><strong>{(catalogue?.count ?? 0).toLocaleString()}</strong> products to explore</span><span><strong>{flagships?.count ?? 0}</strong> flagship shops</span><span><strong>{districts?.count ?? 0}</strong> district outlets</span><Link href="/outlets">{products?.some(p => p.is_demo) ? "Explore the demo network" : "Explore our network"} <Icon name="arrow" width={15} height={15} /></Link></div><div className="benefits-row">{([{ icon: "store", title: "Local outlets, one place", copy: "Discover our growing marketplace" }, { icon: "truck", title: "Delivery to your door", copy: "Review options at checkout" }, { icon: "shield", title: "Pay when it arrives", copy: "Cash on delivery, made simple" }, { icon: "box", title: "Stay in the know", copy: "Follow every order in your account" }] as { icon: IconName; title: string; copy: string }[]).map((item) => <div className="benefit" key={item.title}><Icon name={item.icon} /><span><strong>{item.title}</strong><small>{item.copy}</small></span></div>)}</div>
    <section className="home-section"><div className="section-heading"><div><p className="section-kicker">A place for every pick</p><h2>What’s on your list?</h2></div><Link href="/products" className="text-link">Explore all <Icon name="arrow" /></Link></div><div className="category-row">{categories?.length ? categories.slice(0, 6).map((category, index) => <Link key={category.id} href={`/products?category=${encodeURIComponent(category.slug)}`} className="category-tile"><span className="category-art"><Icon name={collections[index % collections.length].icon} /></span>{category.name_en}</Link>) : collections.map((collection) => <Link key={collection.name} href={collection.search ? `/products?search=${collection.search}` : "/products"} className="category-tile"><span className="category-art"><Icon name={collection.icon} /></span>{collection.name}</Link>)}</div></section>
    <div className="editorial-grid"><section className="editorial-card"><p className="section-kicker">For the everyday table</p><h3>Small essentials.<br />Lovely possibilities.</h3><Link className="text-link" href="/products">Find your next favourite <Icon name="arrow" /></Link><Icon name="leaf" className="editorial-symbol" /></section><section className="editorial-card alt"><p className="section-kicker">From your neighbourhood</p><h3>Local shopping.<br />A little more connected.</h3><Link className="text-link" href="/outlets">Meet our outlets <Icon name="arrow" /></Link><Icon name="store" className="editorial-symbol" /></section></div>
    <section className="home-section"><div className="section-heading"><div><p className="section-kicker">Your everyday discoveries</p><h2>Fresh from the marketplace</h2></div><Link href="/products" className="text-link">Shop all <Icon name="arrow" /></Link></div>{products?.length ? <div className="product-grid">{products.map((product) => <ProductCard key={product.id} product={product} />)}</div> : <div className="empty-state"><span className="empty-icon"><Icon name="bag" /></span><h3>{products ? "Good finds are on their way." : "Let’s try that again."}</h3><p>{products ? "Our marketplace is getting ready for its next arrivals. Explore our outlets while we prepare the shelves." : "We couldn’t load the latest products just now. Please browse the catalogue or try again shortly."}</p><Link href={products ? "/outlets" : "/products"} className="button-secondary">{products ? "Explore outlets" : "Browse products"}<Icon name="arrow" width={15} height={15} /></Link></div>}</section>
    <section className="outlet-banner"><div><p className="section-kicker">Rooted in your neighbourhood</p><h2>Your local favourites. One marketplace.</h2><p>Discover Subah BD outlets and partner sellers. Choose what you love, and we’ll bring your order together.</p></div><Link href="/outlets" className="button-primary">Explore our outlets <Icon name="arrow" width={16} height={16} /></Link></section>
  </>;
}
