"""Checks the locally seeded 2,500-item / 72-location demonstration storefront."""
from pathlib import Path
from playwright.sync_api import sync_playwright, expect

output = Path(__file__).resolve().parents[1] / "test-results"
output.mkdir(exist_ok=True)
with sync_playwright() as playwright:
    browser = playwright.chromium.launch(channel="msedge", headless=True)
    page = browser.new_page(viewport={"width": 1440, "height": 1000})
    page.goto("http://localhost:3000/")
    expect(page.locator(".network-strip")).to_contain_text("2,500", timeout=30000)
    expect(page.locator(".product-card")).to_have_count(8)
    expect(page.locator(".brand-logo").first).to_be_visible()
    page.wait_for_function("Array.from(document.images).every(i=>i.complete)")
    page.screenshot(path=str(output / "storefront-desktop.png"), full_page=True)
    page.goto("http://localhost:3000/products")
    expect(page.locator(".catalog-top")).to_contain_text("2500 products", timeout=30000)
    expect(page.locator(".product-card")).to_have_count(24)
    page.get_by_role("navigation", name="Product pages").get_by_role("link", name="Next").click()
    expect(page.locator(".pagination-bar")).to_contain_text("Page 2")
    page.goto("http://localhost:3000/products?category=demo-rice-grains")
    expect(page.locator(".catalog-top")).to_contain_text("100 products")
    page.locator(".product-card").first.click()
    expect(page.locator(".demo-notice")).to_contain_text("Demo product")
    page.get_by_role("button", name="Add to shopping bag", exact=True).click()
    expect(page.get_by_text("Added to your shopping bag.")).to_be_visible()
    expect(page.get_by_role("link", name="Shopping bag, 1 items")).to_be_visible()
    page.goto("http://localhost:3000/outlets")
    expect(page.locator(".network-toolbar")).to_contain_text("72 locations")
    page.get_by_role("navigation", name="Filter outlets by type").get_by_role("link", name="Flagship shops").click()
    expect(page.locator(".outlet-card")).to_have_count(8)
    page.get_by_role("navigation", name="Filter outlets by division").get_by_role("link", name="Chattogram", exact=True).click()
    expect(page.locator(".outlet-card")).to_have_count(1)
    page.get_by_role("navigation", name="Filter outlets by type").get_by_role("link", name="District outlets").click()
    expect(page.locator(".outlet-card")).to_have_count(11)
    page.screenshot(path=str(output / "outlets-filtered-desktop.png"), full_page=True)
    page.set_viewport_size({"width": 390, "height": 844})
    page.screenshot(path=str(output / "outlets-filtered-mobile.png"), full_page=True)
    assert page.evaluate("document.documentElement.scrollWidth <= window.innerWidth")
    browser.close()
print("Showcase passed: 2,500 products, 24/page, category filter, product detail/cart, 72 locations, division/type filters and mobile layout.")
