# Generated by Django 5.1.2 on 2026-09-17 19:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_checkout_keys(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    for pk in Order.objects.using(schema_editor.connection.alias).values_list('pk', flat=True).iterator():
        Order.objects.using(schema_editor.connection.alias).filter(pk=pk).update(checkout_key=uuid.uuid4())


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PREPARING', 'Preparing'), ('OUT_FOR_DELIVERY', 'Out for delivery'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=32)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AddField(
            model_name='order',
            name='checkout_key',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunPython(backfill_checkout_keys, migrations.RunPython.noop),
        migrations.AlterField(model_name='order', name='checkout_key', field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='BDT', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='request_hash',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='marketplace.inventory'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at', '-id'], name='orders_orde_user_id_81d00f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx'),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillments', to='orders.order'),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillments', to='marketplace.outlet'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fulfillment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='orders.fulfillment'),
        ),
        migrations.AddIndex(
            model_name='fulfillment',
            index=models.Index(fields=['outlet', 'status', '-created_at', '-id'], name='orders_fulf_outlet__5ac036_idx'),
        ),
        migrations.AddConstraint(
            model_name='fulfillment',
            constraint=models.UniqueConstraint(fields=('order', 'outlet'), name='unique_order_outlet'),
        ),
    ]
