# Generated by Django 5.1.2 on 2026-09-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_settlemententry_options_and_more'),
        ('orders', '0002_fulfillment_alter_order_options_order_checkout_key_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fulfillment',
            index=models.Index(fields=['outlet', '-created_at', '-id'], name='orders_fulf_outlet__b7a7cd_idx'),
        ),
        migrations.AddIndex(
            model_name='fulfillment',
            index=models.Index(fields=['created_at'], name='orders_fulf_created_a34d4d_idx'),
        ),
    ]
