'use client';

import Image from "next/image";
import Link from "next/link";
import Price from "@/components/Price";
import Icon from "@/components/Icon";
import { calculateSubtotal, useCartStore } from "@/store/cart.store";

export default function CartPage() {
  const { items, updateQty, removeItem } = useCartStore();
  const subtotal = calculateSubtotal(items);
  return <><div className="breadcrumb"><Link href="/">Home</Link><Icon name="chevron" /><Link href="/products">Marketplace</Link><Icon name="chevron" /><span>Shopping bag</span></div><div className="catalog-top"><div><p className="eyebrow">Your everyday picks</p><h1 className="page-heading mt-3">A bag full of good things.</h1><p className="page-intro">A final look before we bring it all together.</p></div><Link href="/products" className="text-link">Continue exploring <Icon name="arrow" /></Link></div>
    {!items.length ? <div className="empty-state"><span className="empty-icon"><Icon name="bag" /></span><h2>Your next favourite is waiting.</h2><p>Your shopping bag is empty. Explore the marketplace and add something you love.</p><Link href="/products" className="button-primary">Let’s go shopping <Icon name="arrow" width={16} height={16} /></Link></div> : <div className="cart-layout"><section aria-label="Bag items"><div className="flex justify-between border-b border-slate-200 pb-4 text-xs text-slate-500"><span>{items.reduce((sum, item) => sum + item.qty, 0)} items in your bag</span><span>Price</span></div>{items.map((item) => <article key={item.id} className="cart-item"><div className="cart-thumbnail">{item.image ? <Image src={item.image} alt="" fill sizes="92px" className="object-cover" /> : <Icon name="box" width={30} height={30} />}</div><div className="cart-item-info"><h2>{item.name}</h2><small>{item.variantLabel || "Standard pack"} · <Price amount={item.price} /></small><div className="quantity-control"><button aria-label={`Decrease ${item.name} quantity`} disabled={item.qty <= 1} onClick={() => updateQty(item.id, item.qty - 1)}><Icon name="minus" /></button><span aria-live="polite">{item.qty}</span><button aria-label={`Increase ${item.name} quantity`} disabled={item.qty >= 100} onClick={() => updateQty(item.id, item.qty + 1)}><Icon name="plus" /></button></div></div><div className="cart-item-price"><Price amount={item.price * item.qty} /><button onClick={() => removeItem(item.id)} aria-label={`Remove ${item.name}`}>Remove</button></div></article>)}</section><aside className="order-summary"><h2>Your order summary</h2><div className="summary-line"><span>Subtotal</span><Price amount={subtotal} /></div><div className="summary-line"><span>Delivery</span><span>Calculated at checkout</span></div><div className="summary-total"><span>Subtotal</span><Price amount={subtotal} /></div><Link href="/checkout" className="button-primary w-full">Continue to checkout <Icon name="arrow" width={16} height={16} /></Link><p className="summary-footnote">Final prices and outlet availability are confirmed at checkout. Pay in cash when your order arrives.</p><div className="mt-5 flex items-center justify-center gap-2 border-t border-slate-200 pt-5 text-xs text-emerald-700"><Icon name="shield" width={16} height={16} />Cash on delivery</div></aside></div>}
  </>;
}
