# Generated by Django 5.1.2 on 2026-09-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
