# Generated by Django 5.1.2 on 2026-09-21 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_is_demo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('review', 'Review'), ('comment', 'Comment')], max_length=10)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('body', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('verified_purchase', models.BooleanField(default=False, editable=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='catalog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['product', 'kind', 'status', '-created_at'], name='catalog_pro_product_296ce5_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'review')), fields=('product', 'user'), name='one_product_review_per_user'), models.CheckConstraint(condition=models.Q(models.Q(('kind', 'review'), ('rating__gte', 1), ('rating__isnull', False), ('rating__lte', 5)), models.Q(('kind', 'comment'), ('rating__isnull', True)), _connector='OR'), name='feedback_rating_matches_kind')],
            },
        ),
    ]
