# Generated by Django 5.1.2 on 2026-01-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='banners/')),
                ('cta_label', models.CharField(blank=True, max_length=128)),
                ('cta_url', models.URLField(blank=True)),
                ('section', models.CharField(choices=[('hero', 'Hero'), ('flash', 'Flash'), ('promo', 'Promo')], default='hero', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('sort', '-created_at'),
            },
        ),
    ]
