# Generated by Django 5.1.2 on 2026-09-17 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        ('orders', '0002_fulfillment_alter_order_options_order_checkout_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='settlemententry',
            name='fulfillment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement', to='orders.fulfillment'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='marketplace.inventory'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['product', 'variant', 'outlet'], name='marketplace_product_5f6c1a_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', False)), fields=('outlet', 'product', 'variant'), name='unique_outlet_variant'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', True)), fields=('outlet', 'product'), name='unique_outlet_product'),
        ),
        migrations.AddIndex(
            model_name='outlet',
            index=models.Index(fields=['zone', 'is_active', 'priority'], name='marketplace_zone_5dc508_idx'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'seller'), name='unique_seller_member'),
        ),
    ]
