# Generated by Django 5.1.2 on 2026-09-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_initial'),
        ('orders', '0002_fulfillment_alter_order_options_order_checkout_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settlemententry',
            options={},
        ),
        migrations.AddIndex(
            model_name='settlemententry',
            index=models.Index(fields=['created_at'], name='marketplace_created_0b0d5b_idx'),
        ),
    ]
