# Generated by Django 5.1.2 on 2026-09-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_settlemententry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='operation_key',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
