# Generated by Django 5.1.2 on 2026-09-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_stockmovement_operation_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='district',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='outlet',
            name='division',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='outlet',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outlet',
            name='outlet_type',
            field=models.CharField(choices=[('flagship', 'Divisional flagship'), ('district', 'District outlet')], default='district', max_length=16),
        ),
    ]
